sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7.8
  - DJANGO=1.8.6
  - DJANGO=1.9.10
  - DJANGO=1.10.2
install:
  - pip install .
  - pip install -q Django==$DJANGO
before_script:
  - pip freeze
script:
  - python setup.py test
